---

###
### Main entrypoint
###

- include_tasks: remove.yml
  loop_control:
    loop_var: k8s_item
  with_items:
    - "{{ k8s_templates_remove }}"
  when:
    - (
        k8s_remove is defined and not k8s_create is defined
      ) or (
        k8s_remove is not defined and not k8s_create is defined
      )

- include_tasks: create.yml
  loop_control:
    loop_var: k8s_item
  with_items:
    - "{{ k8s_templates_create }}"
  # Alway run when k8s_tag is not defined
  # or only run templates that match k8s_tag values
  when: |
    (
      (
        k8s_create is defined and not k8s_remove is defined
      ) or (
        k8s_create is not defined and not k8s_remove is defined
      )
    ) and (
      (
        k8s_tag is defined and k8s_tag and
        k8s_item.tag is defined and k8s_item.tag and
        k8s_tag == k8s_item.tag
      ) or (
        k8s_tag is defined and k8s_tag and
        k8s_item.tags is defined and k8s_item.tags and
        k8s_tag in k8s_item.tags
      ) or (
        k8s_tag is not defined
      )
    )
